### ISSUE TITLE
Connection Could Not Be Reached Because The Target Machine Actively Refused The Connection

### ISSUE THREAD

**Issue by Technology101** [IceYGO/windbot#1]
I compiled this with Visual Studio, and got the executable running. However, everytime I run it by itself I get the System.Net.Sockets.TcpClient exception.
When I run it after Ygopro has a LAN server of the same IP and Port, the application throws no error and just does nothing. I'm not sure if I am running this app correctly and need help.

Is Windbot intended to work alonside a YgoSharp server, or can it be run with a LAN server?

**Comment by IceYGO** [comment]
WindBot is supposed to be compatible with any YGOPro server, provided that the version is compatible.

This error message means the application tried to connect to a valid computer but using an invalid port. Are you sure the port is correct?

**Comment by Technology101** [comment]
Both Program.cs and the YGOpro LAN are set to the same IP and port #. I am using Fluorohydride's YGOpro source code as the testing grounds for this application. I am just running a LAN connection and then running the Windbot. All the terminal does is recognize the 2 decks and the Game Packet times out (I think) after a minute.
