### ISSUE TITLE
当前版本（0x134a）输入启动参数后直接退出了

### ISSUE THREAD

**Issue by ozxdno** [IceYGO/windbot#113]
我直接下载ZIP文件后打开，在调试选项卡的命令行参数输入：
Deck=Lightsworn
（该卡组和AI类文件都存在了，就没动）
打开YGOpro最新版，建立好了主机（默认参数）
再在调试模式下运行WindBot，结果直接退出了。。
线程 0x5f68 已退出，返回值为 0 (0x0)。
线程 0x67e8 已退出，返回值为 0 (0x0)。
程序“[23216] Bot.vshost.exe”已退出，返回值为 0 (0x0)。

并没有加入游戏并准备 = =！

**Comment by mercury233** [comment]
数据库放进去没

**Comment by ozxdno** [comment]
cdb文件吗？放了

**Comment by mercury233** [comment]
把windbot设为启动项目

**Comment by ozxdno** [comment]
> 把windbot设为启动项目

也设置了。。。

**Comment by mercury233** [comment]
>程序“[23216] Bot.vshost.exe”已退出，返回值为 0 (0x0)。

这里运行的还是BotWrapper

**Comment by ozxdno** [comment]
> > 程序“[23216] Bot.vshost.exe”已退出，返回值为 0 (0x0)。
> 
> 这里运行的还是BotWrapper

什么意思？设置WindBot为启动项，然后我调试模式直接运行了

**Comment by mercury233** [comment]
![image](https://user-images.githubusercontent.com/13391795/59730928-c9be5100-9276-11e9-96ad-b58027163ea0.png)
这里选的哪个

**Comment by ozxdno** [comment]
和你一样

**Comment by mercury233** [comment]
ygopro那边你用的什么版本

**Comment by ozxdno** [comment]
> ygopro那边你用的什么版本

不知道在哪儿看。。，YGO目录下带了WindBot，这个版本应该可以把，168上下载的

**Comment by mercury233** [comment]
![image](https://user-images.githubusercontent.com/13391795/59731050-4a7d4d00-9277-11e9-9449-2a7e9f09d294.png)
这里的版本号

**Comment by ozxdno** [comment]
> ![image](https://user-images.githubusercontent.com/13391795/59731050-4a7d4d00-9277-11e9-9449-2a7e9f09d294.png)
> 这里的版本号

YGOPRO Version:1.034.9

**Comment by mercury233** [comment]
那是你ygopro的版本旧了

**Comment by ozxdno** [comment]
![image](https://user-images.githubusercontent.com/26242905/59731120-8a443480-9277-11e9-85eb-74edcf229e8e.png)
要换个版本试一试？

**Comment by mercury233** [comment]
版本不匹配是肯定不行的

**Comment by ozxdno** [comment]
Mycard下那个版本可以吗

**Comment by mercury233** [comment]
为什么不更新ygopro

**Comment by ozxdno** [comment]
又要去下一个。。我只想看看AI怎么实现的

**Comment by ozxdno** [comment]
> 为什么不更新ygopro

可以了，谢谢！YGOPRO没带自动更新功能把
