### ISSUE TITLE
突进

### ISSUE THREAD

**Issue by jankin-l** [IceYGO/windbot#118]
突进这张卡，期望效果：已方怪兽被攻击时，选中此怪兽并发动
如何能判断出怪兽被攻击？

**Comment by handsomekiwi** [comment]
Card..UnderAttack

**Comment by jankin-l** [comment]
> Card.UnderAttack

感谢~，判断是否是对方回合，用Duel.Turn还是Duel.player

**Comment by mercury233** [comment]
参考DefaultHonestEffect，使用Bot.BattlingMonster

**Comment by jankin-l** [comment]
> 参考DefaultHonestEffect，使用Bot.BattlingMonster

ok,3q~,我回去试试

**Comment by jankin-l** [comment]
我试了两位方法都用上了，感谢~
