### ISSUE TITLE
Error when compile in linux

### ISSUE THREAD

**Issue by ohmpsy** [IceYGO/windbot#13]
Hello i have an error when compile the source in linux. Any suggestion? i followed this steps:

https://github.com/IceYGO/windbot/issues/5

XBuild Engine Version 2.10.8.1
Mono, Version 2.10.8.1
Copyright (C) Marek Sieradzki 2005-2008, Novell 2008-2011.

Build started 26/9/2017 20:04:59.
__________________________________________________
Project "/home/aluno/ygopro/novos/wb/WindBot.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Release|Any CPU".
	Target Build:
		Project "/home/aluno/ygopro/novos/wb/WindBot.csproj" (default target(s)):
/home/aluno/ygopro/novos/wb/WindBot.csproj:  warning : Project has unknown ToolsVersion '12.0'. Using the default tools version '4.0' instead.
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target CoreCompile:
				Tool /usr/bin/dmcs execution started with arguments: /noconfig /optimize+ /out:obj/Release/WindBot.exe Game/AI/AIFunctions.cs Game/AI/CardContainer.cs Game/AI/CardExecutor.cs Game/AI/CardExtension.cs Game/AI/CardSelector.cs Game/AI/DeckAttribute.cs Game/AI/DecksManager.cs Game/AI/Decks/BurnExecutor.cs Game/AI/Decks/DragunityExecutor.cs Game/AI/Decks/FrogExecutor.cs Game/AI/Decks/HorusExecutor.cs Game/AI/Decks/OldSchoolExecutor.cs Game/AI/Decks/Rank5Executor.cs Game/AI/Decks/ZexalWeaponsExecutor.cs Game/AI/DefaultExecutor.cs Game/AI/Dialogs.cs Game/AI/Enums/DangerousMonster.cs Game/AI/Enums/InvincibleMonster.cs Game/AI/Enums/NegateAttackSpell.cs Game/AI/Enums/NegatesEffects.cs Game/AI/Enums/NegatesSpells.cs Game/AI/Enums/NegatesSummons.cs Game/AI/Enums/NegatesTraps.cs Game/AI/Executor.cs Game/AI/ExecutorType.cs Game/BattlePhase.cs Game/BattlePhaseAction.cs Game/ClientCard.cs Game/ClientField.cs Game/Deck.cs Game/Duel.cs Game/GameAI.cs Game/GameBehavior.cs Game/GameClient.cs Game/GamePacketFactory.cs Game/MainPhase.cs Game/MainPhaseAction.cs Game/Room.cs Logger.cs Program.cs Properties/AssemblyInfo.cs /target:exe /define:TRACE /platform:AnyCPU /reference:./Mono.Data.Sqlite.dll /reference:/usr/lib/mono/4.0/System.dll /reference:/usr/lib/mono/4.0/System.Data.dll /reference:./YGOSharp.Network.dll /reference:./YGOSharp.OCGWrapper.dll /reference:./YGOSharp.OCGWrapper.Enums.dll /reference:/usr/lib/mono/4.0/System.Core.dll /reference:/usr/lib/mono/4.0/mscorlib.dll /reference:/usr/lib/mono/4.0/System.Transactions.dll /warn:2
Game/AI/DecksManager.cs(39,51): error CS1525: Unexpected symbol `deck'
Game/AI/DecksManager.cs(39,55): error CS1525: Unexpected symbol `)'
Game/Deck.cs(66,52): error CS1525: Unexpected symbol `id', expecting `.'
Game/Deck.cs(66,54): error CS1525: Unexpected symbol `)', expecting `.'
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/home/aluno/ygopro/novos/wb/WindBot.csproj".-- FAILED
		Done building project "/home/aluno/ygopro/novos/wb/WindBot.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/aluno/ygopro/novos/wb/WindBot.sln".-- FAILED
Done building project "/home/aluno/ygopro/novos/wb/WindBot.sln".-- FAILED

Build FAILED.

Warnings:

/home/aluno/ygopro/novos/wb/WindBot.sln (default targets) ->
(Build target) ->
/home/aluno/ygopro/novos/wb/WindBot.csproj (default targets) ->

	/home/aluno/ygopro/novos/wb/WindBot.csproj:  warning : Project has unknown ToolsVersion '12.0'. Using the default tools version '4.0' instead.

Errors:

/home/aluno/ygopro/novos/wb/WindBot.sln (default targets) ->
(Build target) ->
/home/aluno/ygopro/novos/wb/WindBot.csproj (default targets) ->
/usr/lib/mono/4.0/Microsoft.CSharp.targets (CoreCompile target) ->

	Game/AI/DecksManager.cs(39,51): error CS1525: Unexpected symbol `deck'
	Game/AI/DecksManager.cs(39,55): error CS1525: Unexpected symbol `)'
	Game/Deck.cs(66,52): error CS1525: Unexpected symbol `id', expecting `.'
	Game/Deck.cs(66,54): error CS1525: Unexpected symbol `)', expecting `.'

	 1 Warning(s)
	 4 Error(s)

Time Elapsed 00:00:00.6244640

**Comment by mercury233** [comment]
fixed in https://github.com/IceYGO/windbot/commit/93ad90437728fc217e38a9eb4093bfb1e721ba7b

**Comment by ohmpsy** [comment]
Thanks.
