### ISSUE TITLE
Windbot Add AI_Test2+AI_Test3+AI_Test4 etc.

### ISSUE THREAD

**Issue by TPM5934** [IceYGO/windbot#140]
Sorry, i would like to propose a change to the Windbot. I know it's complicated, but having already entered AI_Test, I ask if you can insert other Decks for Windbot like these, such as AI_Test2, AI_Test3, etc. This is because I would like more ability to insert custom decks against the windbot, no matter the difficulty level, I understand that it would be even more complicated, but I ask this change please, to add more AI_Test.

**Comment by Wind2009-Louse** [comment]
You means using the same executor with different decks?

**Comment by TPM5934** [comment]
To be honest, I would prefer modifications more suitable for some decks, to recover AI_Deck (MR3) from previous versions, such as AI_Bujin, Ai_Burning Abyss, Ai_Mermail, etc. But I understand the degree of difficulty and I do not want to create problems, if I can have more AI_Tests I can also modify personally perhaps altering some scripts and copying cards only for the windbot  (custom cards). I just need to have more chance at least using AI_Tests. If possible at least 4 or 5 AI_Test(s) Decks. I know I ask a lot but Ai_test(s) Decks should be the same scripts, at least I think, and so as not to disturb in the future. I therefore ask you to help me in this please. Thank you very much.

**Comment by TPM5934** [comment]
Sorry, I made this request without getting an answer, I would like to know if it is possible to obtain this update, if I have to wait, or if there are problems. In case I can do it myself, but I would need the necessary material. What should I do?

**Comment by mercury233** [comment]
https://github.com/IceYGO/windbot/commit/1348ee441efe1efa9e7ac943722da67cb882af94
now you can use the new param to set the deck file

**Comment by TPM5934** [comment]
[WindBot.zip](https://github.com/IceYGO/windbot/files/6134514/WindBot.zip)
It doesn't work, if I modify AI_test with AI_test1 and Ai_test2 comes out a random deck. I tried to put the files of this archive in the windbot folder, but I don't think this is the case. I am attaching the windbot file, can you modify this windbot folder in order to insert the ydk files of the Ai_Test (s)? (As I said I need several, if you have to do it, put at least 4 or 5. Can you do something?)

**Comment by mercury233** [comment]
ask https://github.com/ProjectIgnis/windbot to merge https://github.com/IceYGO/windbot/commit/1348ee441efe1efa9e7ac943722da67cb882af94
