### ISSUE TITLE
在windbot/Game/AI/Decks目录下添加了新的cs文件后并重新编译后仍然获取不到新的ai

### ISSUE THREAD

**Issue by Kkyoyo** [IceYGO/windbot#146]
在windbot/Game/AI/Decks目录下添加了新的cs文件后并重新编译后仍然获取不到新的ai，以及修改了对应的bots.json,并添加了新的ydk，但是新的ai没有加进来，同时修改旧的ai是可以执行的，但是新的怎么加进去，求助

**Comment by Kkyoyo** [comment]
> 

感谢回复，我是按照wiki的教程操作的，添加了对应的ydk以及使用生成器生成的对应cs文件，是还要做什么操作吗？AI名字是一一对应的，我用旧的ai的cs文件修改里面的代码指向新的卡组后，新的ai可以使用，是还要在哪个文件里添加对应的新添加cs文件名吗

**Comment by mercury233** [comment]
确保在解决方案资源管理器里有你新添加的文件
`[Deck("Brave", "AI_Brave")]`里第一个是AI名，第二个是卡组文件名，在调用时要用前面那个名字

**Comment by Kkyoyo** [comment]
> 确保在解决方案资源管理器里有你新添加的文件 `[Deck("Brave", "AI_Brave")]`里第一个是AI名，第二个是卡组文件名，在调用时要用前面那个名字

在WindBot.csproj中添加了对应的文件名后解决了问题，因为我并不是c#的开发者，不知道是不是这个原因
