### ISSUE TITLE
bug on "finger-guessing"

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [IceYGO/windbot#16]
![83](https://user-images.githubusercontent.com/26178665/35309058-85cbc974-00e5-11e8-8ef3-99dae037e64c.png)

**Comment by OhnkytaBlabdey** [comment]
I run 2 windbot and they seem to get into a circle on finger guessing.

**Comment by mercury233** [comment]
since it seems that you changed many codes, i guess nobody but you can find the reason...
`OnRockPaperScissors` return random value at default, unless you set the `Hand` parameter.
