### ISSUE TITLE
Monster reborn solution

### ISSUE THREAD

**Issue by handsomekiwi** [IceYGO/windbot#25]
有些monster需要先正规特召后，才能用monster reborn 復活他，如果非正规特召就在墓地裡，那隻monster便无法特召
在用monster reborn 时，要如何判断墓地 的monster 无法特召呢

**Comment by mercury233** [comment]
好像没有什么好办法，将来大概可以记录正规特殊召唤成功的事件做标记
（我不记得ygopro本身有没有这个记录了）
