### ISSUE TITLE
Selctcard issue

### ISSUE THREAD

**Issue by handsomekiwi** [IceYGO/windbot#26]
如用SelectCard 选择多种卡片时，如下: 
AI.SelectCard(new[]
                {
                CardId.a,
                CardId.b,
                CardId.c,
                });
如何判断他选择到的是哪一个card.id呢?

**Comment by mercury233** [comment]
选择时由上至下查看list里的卡是否在可选列表里

**Comment by handsomekiwi** [comment]
不太懂你的意思，能举例吗

**Comment by mercury233** [comment]
可选列表里有
黑魔导，青眼白龙，星尘龙，希望皇
你写了
AI.SelectCard(new[]
{
红莲魔龙,
星尘龙
});
程序选择时，首先看可选列表里有没有红莲魔龙，有就选上，然后看有没有星尘龙

**Comment by handsomekiwi** [comment]
我是想看程序选择拿个去做判断，比如

黑魔导，青眼白龙，星尘龙，希望皇
你写了
AI.SelectCard(new[]
{
红莲魔龙,
星尘龙
});
if(ai.Select(星尘龙))
{
做a
}
if(ai.Select(红莲魔龙))
{
做b
}

**Comment by mercury233** [comment]
这个只能自己重写OnSelectCard来判断了，参考青眼的那个
