### ISSUE TITLE
"tick" problem

### ISSUE THREAD

**Issue by YuGiOhMoDDeR** [IceYGO/windbot#8]
is windbot compatible with 0x1339 version? im having issue it won't "tick" lik in screenshot below
http://i.imgur.com/Wm3YqeR.png?1

**Comment by Zayelion** [comment]
Modify this line https://github.com/IceYGO/windbot/blob/master/Program.cs#L12 then recompile.

**Comment by YuGiOhMoDDeR** [comment]
already done it , Zay..with unmodified line, it dont even connect..when i modify it, it connects, but no "check" symbol :/ no idea what could be problem :S

**Comment by Zayelion** [comment]
The deck might be invalid for that banlist, or the server formatting might be different. I doubt the former but what is the server you are connecting to. A local ygosharp instance?

**Comment by YuGiOhMoDDeR** [comment]
you were right, it was about banlist :D it connects fine and with ticked checkbox ^.^
